name: Puppeteer Automation

on:
  schedule:
    - cron: '0 */7 * * *' # Run every 7 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest

    concurrency:
      group: puppeteer-job
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure State Directory
        run: mkdir -p ./state

      - name: Download State Artifact
        uses: actions/download-artifact@v3
        with:
          name: puppeteer-state
          path: ./state
        continue-on-error: true

      - name: Initialize last_index.json if Missing
        run: |
          if [ ! -f ./state/last_index.json ]; then
            echo '{"lastIndex": 0}' > ./state/last_index.json
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Puppeteer Script
        env:
          LAST_INDEX_PATH: ./state/last_index.json
        run: node new.js

      - name: Upload State Artifact
        uses: actions/upload-artifact@v3
        with:
          name: puppeteer-state
          path: ./state
