name: Puppeteer Automation

on:
  schedule:
    - cron: "0 */7 * * *" # Run every 7 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest

    concurrency:
      group: puppeteer-job
      cancel-in-progress: true # Cancels any in-progress job in this group

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Ensure state directory exists
      - name: Ensure State Directory
        run: mkdir -p ./state

      # Download previous state artifact
      - name: Download State Artifact
        uses: actions/download-artifact@v3
        with:
          name: puppeteer-state
          path: ./state
        continue-on-error: true

      # Debug state file before script
      - name: Debug State File Before Script
        run: |
          if [ ! -f ./state/last_index.json ]; then
            echo '{"lastIndex": 0}' > ./state/last_index.json
          fi
          cat ./state/last_index.json

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Chromium dependencies
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libgbm1

      # Install Puppeteer dependencies
      - name: Install Dependencies
        run: npm install

      # Run Puppeteer script
      - name: Run Puppeteer Script
        env:
          LAST_INDEX_PATH: ./state/last_index.json
        run: node new.js

      # Debug state file after script
      - name: Debug State File After Script
        run: cat ./state/last_index.json

      # Upload updated state artifact
      - name: Upload State Artifact
        uses: actions/upload-artifact@v3
        with:
          name: puppeteer-state
          path: ./state
